### ISSUE TITLE
Unable to run Project with basic Example provided

### ISSUE THREAD

**Issue by tayyab-sarwar** [mneil/MongoMatch#1]
Can you explain step by step guide to run the project on the local machine?

**Comment by mneil** [comment]
Hi @tayyab-sarwar unfortunately not. I don't know if I remember where to begin here. The main idea behind this project was to keep in sync two mongo masters. I started it on my own but eventually brought it in under a company I worked for at the time. This was a rough start of where I was and privately it's changed a lot. I would use this as a starting point at best to do the same.

One thing to note the initial merge done in this repo requires an entire collection to be pulled into memory. This worked great/fast in the beginning but I eventually ran into limits since most of our deployments were on-prem with limited hardware. I had to refactor the entire thing to stream the collections and join record by record and replay operations on the databases.
